[package]
name = "gochibbq/restaurant"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Cmdr = "evaera/cmdr@1.12.0"
ZonePlus = "mattschrubb/zoneplus@3.2.0"
Knit = "sleitnick/knit@1.7.0"
Promise = "evaera/promise@4.0.0"
Signal = "sleitnick/signal@2.0.1"
TableUtil = "sleitnick/table-util@1.2.1"
PagesUtil = "colbert2677/pagesutil@2.0.0"
Trove = "sleitnick/trove@1.1.0"